/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mdbwatch;

/** Main application entry-point. */
public final class App {

    private App() {
        // the constructor will never be called directly.
    }

    public static void main(final String[] args) {
        Launcher.run(args);
    }
}
