/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mdbwatch;
/*
 * Si vuole realizzare un applicativo che sia una via di mezzo tra IMDb e JustWatch.
 * Il primo è un database di film, serie tv e tutto ciò che gli gira attorno(attori,
 * registi, sceneggiatori, artisti musicali, location, premi, produzioni ecc...) che
 * consente agli utenti di esprimere un voto su un film, una serie tv, una stagione
 * di una serie tv e il singolo episodio della serie tv. Il secondo consente di cercare
 * film e serie tv e di ottenere i servizi di streaming che ne consentono la visione.
 * Oltre queste funzionalità ogni utente può creare la propria watchlist. Il progetto
 * realizzerà tutto ciò che è stato descritto prima con le opportune operazioni di
 * ricerca ed inserimento.
 */
/** Main application entry-point. */
public final class App {

    private App() {
        // the constructor will never be called directly.
    }

    public static void main(final String[] args) {
    	
    	Launcher.run(args);
    }
}
